import * as FirebaseFirestore from '@google-cloud/firestore';
import * as admin from 'firebase-admin';
import * as firebase from 'firebase';
import { BatchType } from './batch';
import { Base, property } from './base';
import { SubCollection } from './subCollection';
import { NestedCollection } from './nestedCollection';
import { ReferenceCollection } from './referenceCollection';
import { File } from './file';
export { BatchType, Base, property, SubCollection, NestedCollection, ReferenceCollection, File };
export declare let firestore: admin.firestore.Firestore | firebase.firestore.Firestore;
export declare let timestamp: FirebaseFirestore.FieldValue;
export declare const initialize: (app: firebase.app.App | admin.app.App, serverTimestamp: FirebaseFirestore.FieldValue | firebase.firestore.FieldValue) => void;
